from typing import Any
def __getattr__(name: str) -> Any: ...
class SX:
    def __new__(cls, *args: Any, **kwargs: Any) -> "SX": ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __neg__(self) -> Any: ...
    @staticmethod
    def sym(*args: Any, **kwargs: Any) -> "SX": ...
    @staticmethod
    def zeros(*args: Any, **kwargs: Any) -> "SX": ...
    @staticmethod
    def eye(*args: Any, **kwargs: Any) -> "SX": ...
class MX:
    def __new__(cls, *args: Any, **kwargs: Any) -> "MX": ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
class DM:
    def __new__(cls, *args: Any, **kwargs: Any) -> "DM": ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
class Function:
    def __new__(cls, *args: Any, **kwargs: Any) -> "Function": ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
